### ISSUE TITLE
vglrun no respondence

### ISSUE THREAD

**Issue by renhaofan** [accetto/headless-drawing-g3#4] opened 2022-05-09 10:30 UTC
I met the same problem as described in [Container doesn't start with volume .X11-unix:rw](https://github.com/accetto/ubuntu-vnc-xfce-g3/discussions/10#discussioncomment-773317).
I follow your advice, manually change the `DISPLAY`:
``` 
docker run -it --rm \
    --device /dev/dri/card0 \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -e DISPLAY=:2 \
    -p "35000:5901" \
    -p "35001:6901" \
    -e VNC_PW="" \
    accetto/ubuntu-vnc-xfce-opengl-g3:latest --tail-vnc
```
After that, I run the command `vglrun glmark2`, no correspondence. 

Then I run the command `vglrun -d :2 glmark2`, but error occurred like below:

```
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     Mesa/X.org
    GL_RENDERER:   llvmpipe (LLVM 12.0.0, 256 bits)
    GL_VERSION:    3.1 Mesa 21.2.6
=======================================================
[build] use-vbo=false:X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Serial number of failed request:  43
  Current serial number in output stream:  44

```
However, `vglrun -d :2 glxgears` look like good, and no error reported, but it's slower:
```
headless@2ba116776775:~$ glxgears
11525 frames in 5.0 seconds = 2304.955 FPS
11898 frames in 5.0 seconds = 2379.447 FPS
X connection to :2.0 broken (explicit kill or server shutdown).
headless@2ba116776775:~$ vglrun -d :2 glxgears
4714 frames in 5.0 seconds = 942.387 FPS
4937 frames in 5.0 seconds = 987.321 FPS
[VGL] ERROR: in readback--
[VGL]    269: Window has been deleted by window manager
headless@2ba116776775:~$ 

```

**Comment by accetto** [comment] 2022-05-10 08:51
Thanks for the feedback. I'll check it and let you know.

**Comment by accetto** [comment] 2022-05-11 17:48
Hallo @renhaofan,

I can confirm that the command `vglrun -d :2 glmark2` (and also `vglrun -d :1 glmark2`) does not work correctly. It opens the rendering window and it closes it immediatelly. Unfortunately I cannot explain the reason.

However, I don't find such an example on the [page](https://github.com/accetto/ubuntu-vnc-xfce-g3/discussions/10#discussioncomment-773317) you've mentioned above. 

There is only the command `vglrun glmark2`, which works correctly independently of the display number.

Regards,
accetto

**Comment by renhaofan** [comment] 2022-05-12 07:54
> Hallo @renhaofan,
> 
> I can confirm that the command `vglrun -d :2 glmark2` (and also `vglrun -d :1 glmark2`) does not work correctly. It opens the rendering window and it closes it immediatelly. Unfortunately I cannot explain the reason.
> 
> However, I don't find such an example on the [page](https://github.com/accetto/ubuntu-vnc-xfce-g3/discussions/10#discussioncomment-773317) you've mentioned above.
> 
> There is only the command `vglrun glmark2`, which works correctly independently of the display number.
> 
> Regards, accetto

Thanks for your quick response. I have tried some docker images with virtualGL, but all failed.  From your repo, I realize myebe that because `${DISPLAY}`  and `QT_X11_NO_MITSHM` . Next week,  I will try to solve this problem. If I solved that, I will let you know.  Anyway, thanks a lot.

**Comment by accetto** [comment] 2022-05-12 08:34
You're welcome.

I hope you've found that you can override the VNC/noVNC parameters, including the display number, using an external file. It can simplify experimenting. Check the part **At VNC/noVNC startup-time** in this [Readme](https://github.com/accetto/ubuntu-vnc-xfce-g3/blob/master/docker/xfce/README.md#overriding-vncnovnc-parameters) file.

**Comment by renhaofan** [comment] 2022-05-12 09:06
> You're welcome.
> 
> I hope you've found that you can override the VNC/noVNC parameters, including the display number, using an external file. It can simplify experimenting. Check the part **At VNC/noVNC startup-time** in this [Readme](https://github.com/accetto/ubuntu-vnc-xfce-g3/blob/master/docker/xfce/README.md#overriding-vncnovnc-parameters) file.

Yes. Before I created the issue, I have noticed that and test. Thanks for you remind.

**Comment by accetto** [comment] 2022-05-20 08:41
FYI: I've just updated the images on Docker Hub. There is a newer **VirtualGL 3.0.1**. Maybe it will help.

**Comment by renhaofan** [comment] 2022-05-20 09:11
> FYI: I've just updated the images on Docker Hub. There is a newer **VirtualGL 3.0.1**. Maybe it will help.

I will try that later and let you know if successful.
 
By the way, I use this [docker image](https://hub.docker.com/r/gezp/ubuntu-desktop)  to solve the VirtualGL problem, which is based on the nomachine with VirtualGL naturely.  And I noticed you comment   the nomachine in your Dockerfile. I hope that docker image is helpful for you.

**Comment by accetto** [comment] 2022-07-07 07:31
Closing because of no further actions from the requester.

I do not have the appropriate hardware to develop the subject at the moment.

**Closed as completed by accetto** 2022-07-07 07:31 UTC
Labels: question
